# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Reglas estrictas para calidad de código
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_print: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    
    # Warnings de estilo (opcionales para desarrollo)
    prefer_expression_function_bodies: false  # Deshabilitado para evitar problemas
    prefer_int_literals: false  # Deshabilitado para evitar problemas
    directives_ordering: false  # Deshabilitado para evitar problemas
    unawaited_futures: false  # Deshabilitado para evitar problemas
    unnecessary_lambdas: true  # Mantener habilitado
    
    # Reglas de seguridad
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    
    # Reglas de rendimiento
    prefer_const_constructors_in_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Reglas de mantenibilidad
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_in_for_each: true
    prefer_initializing_formals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_spread_collections: true
    recursive_getters: true
    slash_for_doc_comments: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unnecessary_await_in_return: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_null_checks: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    use_build_context_synchronously: true
    use_rethrow_when_possible: true
    valid_regexps: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/l10n/app_localizations.dart"
    - "**/l10n/app_localizations_*.dart"
    - "**/scripts/*.dart"
  
  errors:
    # Errores críticos que deben ser corregidos
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    non_constant_identifier_names: error
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    prefer_const_declarations: error
    avoid_print: error
    use_key_in_widget_constructors: error
    
    # Warnings de estilo como info (no bloquean el desarrollo)
    prefer_expression_function_bodies: info
    prefer_int_literals: info
    directives_ordering: info
    unawaited_futures: info
    unnecessary_lambdas: info
    
    # Excluir warnings de scripts de desarrollo
    avoid_slow_async_io: ignore
