import 'package:json_annotation/json_annotation.dart';

part 'task.g.dart';

/// Modelo que representa una tarea en el sistema de gestión de proyectos.
///
/// Mapea a la tabla `tasks` de Supabase y contiene toda la información
/// necesaria para la gestión de tareas: metadatos, estado, fechas, asignaciones
/// y posicionamiento en el sistema Kanban.
///
/// ## Propiedades principales:
/// - [id]: Identificador único autoincremental
/// - [title]: Título de la tarea (requerido)
/// - [description]: Descripción detallada de la tarea
/// - [status]: Estado actual de la tarea
/// - [dueDate]: Fecha límite de la tarea (opcional)
/// - [kanbanPosition]: Posición en el tablero Kanban
/// - [complexity]: Nivel de complejidad de la tarea
/// - [estimatedHours]: Horas estimadas de trabajo
/// - [actualHours]: Horas reales trabajadas
///
/// ## Ejemplo JSON:
/// ```json
/// {
///   "id": 1,
///   "title": "Implementar autenticación",
///   "description": "Crear sistema de login con Supabase Auth",
///   "status": "in_progress",
///   "due_date": "2025-02-01T00:00:00Z",
///   "complexity": "medium",
///   "estimated_hours": 8,
///   "created_at": "2025-01-01T00:00:00Z"
/// }
/// ```
///
/// ## Estados posibles:
/// - [pending]: Tarea pendiente de iniciar
/// - [in_progress]: Tarea en progreso
/// - [completed]: Tarea completada
///
/// Ver también: [TaskStatus], [TaskComplexity]
@JsonSerializable()
class Task {
  final int id;
  @JsonKey(name: 'project_id')
  final int? projectId;
  @JsonKey(name: 'anteproject_id')
  final int? anteprojectId;
  @JsonKey(name: 'milestone_id')
  final int? milestoneId;
  final String title;
  final String description;
  final TaskStatus status;
  @JsonKey(name: 'due_date')
  final DateTime? dueDate;
  @JsonKey(name: 'completed_at')
  final DateTime? completedAt;
  @JsonKey(name: 'kanban_position')
  final double? kanbanPosition;
  @JsonKey(name: 'estimated_hours')
  final int? estimatedHours;
  @JsonKey(name: 'actual_hours')
  final int? actualHours;
  final TaskComplexity complexity;
  final List<String>? tags;
  @JsonKey(name: 'is_auto_generated')
  final bool isAutoGenerated;
  @JsonKey(name: 'generation_source')
  final String? generationSource;
  @JsonKey(name: 'created_at')
  final DateTime createdAt;
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  const Task({
    required this.id,
    this.projectId,
    this.anteprojectId,
    this.milestoneId,
    required this.title,
    required this.description,
    required this.status,
    this.dueDate,
    this.completedAt,
    this.kanbanPosition,
    this.estimatedHours,
    this.actualHours,
    required this.complexity,
    this.tags,
    required this.isAutoGenerated,
    this.generationSource,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);
  Map<String, dynamic> toJson() => _$TaskToJson(this);

  Task copyWith({
    int? id,
    int? projectId,
    int? anteprojectId,
    int? milestoneId,
    String? title,
    String? description,
    TaskStatus? status,
    DateTime? dueDate,
    DateTime? completedAt,
    double? kanbanPosition,
    int? estimatedHours,
    int? actualHours,
    TaskComplexity? complexity,
    List<String>? tags,
    bool? isAutoGenerated,
    String? generationSource,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Task(
      id: id ?? this.id,
      projectId: projectId ?? this.projectId,
      anteprojectId: anteprojectId ?? this.anteprojectId,
      milestoneId: milestoneId ?? this.milestoneId,
      title: title ?? this.title,
      description: description ?? this.description,
      status: status ?? this.status,
      dueDate: dueDate ?? this.dueDate,
      completedAt: completedAt ?? this.completedAt,
      kanbanPosition: kanbanPosition ?? this.kanbanPosition,
      estimatedHours: estimatedHours ?? this.estimatedHours,
      actualHours: actualHours ?? this.actualHours,
      complexity: complexity ?? this.complexity,
      tags: tags ?? this.tags,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      generationSource: generationSource ?? this.generationSource,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() {
    return 'Task(id: $id, title: $title, status: $status, projectId: $projectId)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is Task && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}

/// Estados posibles de una tarea en el flujo de trabajo.
enum TaskStatus {
  /// Tarea pendiente de iniciar.
  @JsonValue('pending')
  pending,

  /// Tarea en progreso de desarrollo.
  @JsonValue('in_progress')
  inProgress,

  /// Tarea completada y finalizada.
  @JsonValue('completed')
  completed,
}

/// Niveles de complejidad de una tarea.
enum TaskComplexity {
  /// Tarea simple, requiere poco tiempo y esfuerzo.
  @JsonValue('simple')
  simple,

  /// Tarea de complejidad media, requiere tiempo moderado.
  @JsonValue('medium')
  medium,

  /// Tarea compleja, requiere mucho tiempo y esfuerzo.
  @JsonValue('complex')
  complex,
}

extension TaskStatusExtension on TaskStatus {
  // Los métodos displayName y shortName ahora requieren AppLocalizations
  // Se moverán a un helper o se usarán directamente en los widgets

  bool get isCompleted => this == TaskStatus.completed;
  bool get isInProgress => this == TaskStatus.inProgress;
  bool get isPending => this == TaskStatus.pending;

  /// Convierte el enum a su valor de base de datos (snake_case)
  String get dbValue {
    switch (this) {
      case TaskStatus.pending:
        return 'pending';
      case TaskStatus.inProgress:
        return 'in_progress';
      case TaskStatus.completed:
        return 'completed';
    }
  }
}

extension TaskComplexityExtension on TaskComplexity {
  // El método displayName ahora requiere AppLocalizations
  // Se usará directamente en los widgets

  String get dbValue {
    switch (this) {
      case TaskComplexity.simple:
        return 'simple';
      case TaskComplexity.medium:
        return 'medium';
      case TaskComplexity.complex:
        return 'complex';
    }
  }

  int get estimatedHours {
    switch (this) {
      case TaskComplexity.simple:
        return 2;
      case TaskComplexity.medium:
        return 8;
      case TaskComplexity.complex:
        return 24;
    }
  }
}
