// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'task.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Task _$TaskFromJson(Map<String, dynamic> json) => Task(
  id: (json['id'] as num).toInt(),
  projectId: (json['projectId'] as num).toInt(),
  milestoneId: (json['milestoneId'] as num?)?.toInt(),
  title: json['title'] as String,
  description: json['description'] as String,
  status: $enumDecode(_$TaskStatusEnumMap, json['status']),
  dueDate: json['dueDate'] == null
      ? null
      : DateTime.parse(json['dueDate'] as String),
  completedAt: json['completedAt'] == null
      ? null
      : DateTime.parse(json['completedAt'] as String),
  kanbanPosition: (json['kanbanPosition'] as num).toInt(),
  estimatedHours: (json['estimatedHours'] as num?)?.toInt(),
  actualHours: (json['actualHours'] as num?)?.toInt(),
  complexity: $enumDecode(_$TaskComplexityEnumMap, json['complexity']),
  tags: (json['tags'] as List<dynamic>?)?.map((e) => e as String).toList(),
  isAutoGenerated: json['isAutoGenerated'] as bool,
  generationSource: json['generationSource'] as String?,
  createdAt: DateTime.parse(json['createdAt'] as String),
  updatedAt: DateTime.parse(json['updatedAt'] as String),
);

Map<String, dynamic> _$TaskToJson(Task instance) => <String, dynamic>{
  'id': instance.id,
  'projectId': instance.projectId,
  'milestoneId': instance.milestoneId,
  'title': instance.title,
  'description': instance.description,
  'status': _$TaskStatusEnumMap[instance.status]!,
  'dueDate': instance.dueDate?.toIso8601String(),
  'completedAt': instance.completedAt?.toIso8601String(),
  'kanbanPosition': instance.kanbanPosition,
  'estimatedHours': instance.estimatedHours,
  'actualHours': instance.actualHours,
  'complexity': _$TaskComplexityEnumMap[instance.complexity]!,
  'tags': instance.tags,
  'isAutoGenerated': instance.isAutoGenerated,
  'generationSource': instance.generationSource,
  'createdAt': instance.createdAt.toIso8601String(),
  'updatedAt': instance.updatedAt.toIso8601String(),
};

const _$TaskStatusEnumMap = {
  TaskStatus.pending: 'pending',
  TaskStatus.inProgress: 'in_progress',
  TaskStatus.underReview: 'under_review',
  TaskStatus.completed: 'completed',
};

const _$TaskComplexityEnumMap = {
  TaskComplexity.simple: 'simple',
  TaskComplexity.medium: 'medium',
  TaskComplexity.complex: 'complex',
};
