import 'package:json_annotation/json_annotation.dart';

part 'task.g.dart';

@JsonSerializable()
class Task {
  final int id;
  final int projectId;
  final int? milestoneId;
  final String title;
  final String description;
  final TaskStatus status;
  final DateTime? dueDate;
  final DateTime? completedAt;
  final int kanbanPosition;
  final int? estimatedHours;
  final int? actualHours;
  final TaskComplexity complexity;
  final List<String>? tags;
  final bool isAutoGenerated;
  final String? generationSource;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Task({
    required this.id,
    required this.projectId,
    this.milestoneId,
    required this.title,
    required this.description,
    required this.status,
    this.dueDate,
    this.completedAt,
    required this.kanbanPosition,
    this.estimatedHours,
    this.actualHours,
    required this.complexity,
    this.tags,
    required this.isAutoGenerated,
    this.generationSource,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);
  Map<String, dynamic> toJson() => _$TaskToJson(this);

  Task copyWith({
    int? id,
    int? projectId,
    int? milestoneId,
    String? title,
    String? description,
    TaskStatus? status,
    DateTime? dueDate,
    DateTime? completedAt,
    int? kanbanPosition,
    int? estimatedHours,
    int? actualHours,
    TaskComplexity? complexity,
    List<String>? tags,
    bool? isAutoGenerated,
    String? generationSource,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Task(
      id: id ?? this.id,
      projectId: projectId ?? this.projectId,
      milestoneId: milestoneId ?? this.milestoneId,
      title: title ?? this.title,
      description: description ?? this.description,
      status: status ?? this.status,
      dueDate: dueDate ?? this.dueDate,
      completedAt: completedAt ?? this.completedAt,
      kanbanPosition: kanbanPosition ?? this.kanbanPosition,
      estimatedHours: estimatedHours ?? this.estimatedHours,
      actualHours: actualHours ?? this.actualHours,
      complexity: complexity ?? this.complexity,
      tags: tags ?? this.tags,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      generationSource: generationSource ?? this.generationSource,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() {
    return 'Task(id: $id, title: $title, status: $status, projectId: $projectId)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is Task && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}

enum TaskStatus {
  @JsonValue('pending')
  pending,
  @JsonValue('in_progress')
  inProgress,
  @JsonValue('under_review')
  underReview,
  @JsonValue('completed')
  completed,
}

enum TaskComplexity {
  @JsonValue('simple')
  simple,
  @JsonValue('medium')
  medium,
  @JsonValue('complex')
  complex,
}

extension TaskStatusExtension on TaskStatus {
  String get displayName {
    switch (this) {
      case TaskStatus.pending:
        return 'Pendiente';
      case TaskStatus.inProgress:
        return 'En Progreso';
      case TaskStatus.underReview:
        return 'En Revisión';
      case TaskStatus.completed:
        return 'Completada';
    }
  }

  String get shortName {
    switch (this) {
      case TaskStatus.pending:
        return 'Pendiente';
      case TaskStatus.inProgress:
        return 'Progreso';
      case TaskStatus.underReview:
        return 'Revisión';
      case TaskStatus.completed:
        return 'Completada';
    }
  }

  bool get isCompleted => this == TaskStatus.completed;
  bool get isInProgress => this == TaskStatus.inProgress;
  bool get isPending => this == TaskStatus.pending;
  bool get isUnderReview => this == TaskStatus.underReview;
}

extension TaskComplexityExtension on TaskComplexity {
  String get displayName {
    switch (this) {
      case TaskComplexity.simple:
        return 'Simple';
      case TaskComplexity.medium:
        return 'Media';
      case TaskComplexity.complex:
        return 'Compleja';
    }
  }

  int get estimatedHours {
    switch (this) {
      case TaskComplexity.simple:
        return 2;
      case TaskComplexity.medium:
        return 8;
      case TaskComplexity.complex:
        return 24;
    }
  }
}
