// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'task.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Task _$TaskFromJson(Map<String, dynamic> json) => Task(
  id: (json['id'] as num).toInt(),
  projectId: (json['project_id'] as num?)?.toInt(),
  anteprojectId: (json['anteproject_id'] as num?)?.toInt(),
  milestoneId: (json['milestone_id'] as num?)?.toInt(),
  title: json['title'] as String,
  description: json['description'] as String,
  status: $enumDecode(_$TaskStatusEnumMap, json['status']),
  dueDate: json['due_date'] == null
      ? null
      : DateTime.parse(json['due_date'] as String),
  completedAt: json['completed_at'] == null
      ? null
      : DateTime.parse(json['completed_at'] as String),
  kanbanPosition: (json['kanban_position'] as num?)?.toInt(),
  estimatedHours: (json['estimated_hours'] as num?)?.toInt(),
  actualHours: (json['actual_hours'] as num?)?.toInt(),
  complexity: $enumDecode(_$TaskComplexityEnumMap, json['complexity']),
  tags: (json['tags'] as List<dynamic>?)?.map((e) => e as String).toList(),
  isAutoGenerated: json['is_auto_generated'] as bool,
  generationSource: json['generation_source'] as String?,
  createdAt: DateTime.parse(json['created_at'] as String),
  updatedAt: DateTime.parse(json['updated_at'] as String),
);

Map<String, dynamic> _$TaskToJson(Task instance) => <String, dynamic>{
  'id': instance.id,
  'project_id': instance.projectId,
  'anteproject_id': instance.anteprojectId,
  'milestone_id': instance.milestoneId,
  'title': instance.title,
  'description': instance.description,
  'status': _$TaskStatusEnumMap[instance.status]!,
  'due_date': instance.dueDate?.toIso8601String(),
  'completed_at': instance.completedAt?.toIso8601String(),
  'kanban_position': instance.kanbanPosition,
  'estimated_hours': instance.estimatedHours,
  'actual_hours': instance.actualHours,
  'complexity': _$TaskComplexityEnumMap[instance.complexity]!,
  'tags': instance.tags,
  'is_auto_generated': instance.isAutoGenerated,
  'generation_source': instance.generationSource,
  'created_at': instance.createdAt.toIso8601String(),
  'updated_at': instance.updatedAt.toIso8601String(),
};

const _$TaskStatusEnumMap = {
  TaskStatus.pending: 'pending',
  TaskStatus.inProgress: 'in_progress',
  TaskStatus.underReview: 'under_review',
  TaskStatus.completed: 'completed',
};

const _$TaskComplexityEnumMap = {
  TaskComplexity.simple: 'simple',
  TaskComplexity.medium: 'medium',
  TaskComplexity.complex: 'complex',
};
