import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:mockito/mockito.dart';
import 'package:mockito/annotations.dart';

import 'package:frontend/services/auth_service.dart';
import 'package:frontend/services/anteprojects_service.dart';
import 'package:frontend/services/tasks_service.dart';
import 'package:frontend/models/user.dart';
import 'package:frontend/models/anteproject.dart';
import 'package:frontend/models/task.dart';
import 'package:frontend/l10n/app_localizations.dart';
import 'widget_test_utils.mocks.dart';

// Generar mocks
@GenerateMocks([AuthService, AnteprojectsService, TasksService])
/// Utilidades comunes para tests de widgets
class WidgetTestUtils {
  /// Crear MaterialApp con BlocProvider para testing
  static Widget createTestApp({
    required Widget child,
    List<BlocProvider> blocProviders = const [],
  }) {
    final content = blocProviders.isEmpty
        ? child
        : MultiBlocProvider(providers: blocProviders, child: child);

    return MaterialApp(
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      locale: const Locale('es', 'ES'),
      home: content,
    );
  }

  /// Crear MaterialApp con navegación para testing
  static Widget createTestAppWithNavigation({
    required Widget child,
    List<BlocProvider> blocProviders = const [],
  }) {
    final content = blocProviders.isEmpty
        ? child
        : MultiBlocProvider(providers: blocProviders, child: child);

    return MaterialApp(
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      locale: const Locale('es', 'ES'),
      routes: {
        '/': (context) => content,
        '/login': (context) => const Scaffold(body: Text('Login')),
        '/dashboard': (context) => const Scaffold(body: Text('Dashboard')),
      },
      home: content,
    );
  }

  /// Crear usuario de prueba
  static User createTestUser({
    int id = 1,
    String email = 'test@example.com',
    String fullName = 'Test User',
    UserRole role = UserRole.student,
    UserStatus status = UserStatus.active,
  }) {
    final now = DateTime.now();
    return User(
      id: id,
      email: email,
      fullName: fullName,
      role: role,
      status: status,
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Crear anteproyecto de prueba
  static Anteproject createTestAnteproject({
    int id = 1,
    String title = 'Test Anteproject',
    String description = 'Test Description',
    ProjectType projectType = ProjectType.execution,
    String academicYear = '2024-2025',
    AnteprojectStatus status = AnteprojectStatus.draft,
    int tutorId = 1,
  }) {
    final now = DateTime.now();
    return Anteproject(
      id: id,
      title: title,
      projectType: projectType,
      description: description,
      objectives: 'Test objectives for the project',
      academicYear: academicYear,
      expectedResults: {'result1': 'Expected result 1'},
      timeline: {'phase1': 'Phase 1 description'},
      status: status,
      tutorId: tutorId,
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Crear tarea de prueba
  static Task createTestTask({
    int id = 1,
    int? projectId,
    int? anteprojectId,
    TaskStatus status = TaskStatus.pending,
    TaskComplexity complexity = TaskComplexity.simple,
  }) {
    final now = DateTime(2024, 1, 1);
    return Task(
      id: id,
      projectId: projectId,
      anteprojectId: projectId == null ? anteprojectId : null,
      title: 'Test Task',
      description: 'Test Description',
      status: status,
      complexity: complexity,
      kanbanPosition: 0,
      isAutoGenerated: false,
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Configurar mocks básicos
  static void setupBasicMocks({
    required MockAuthService mockAuthService,
    required MockAnteprojectsService mockAnteprojectsService,
    required MockTasksService mockTasksService,
  }) {
    // Mock AuthService
    when(mockAuthService.isAuthenticated).thenReturn(true);
    when(
      mockAuthService.authStateChanges,
    ).thenAnswer((_) => const Stream.empty());

    // Mock AnteprojectsService
    when(
      mockAnteprojectsService.getAnteprojects(),
    ).thenAnswer((_) async => [createTestAnteproject()]);
    when(
      mockAnteprojectsService.getStudentAnteprojects(),
    ).thenAnswer((_) async => [createTestAnteproject()]);

    // Mock TasksService
    when(
      mockTasksService.getTasks(),
    ).thenAnswer((_) async => [createTestTask()]);
    when(
      mockTasksService.getStudentTasks(),
    ).thenAnswer((_) async => [createTestTask().toJson()]);
    when(
      mockTasksService.getProjectTasksForUser(1),
    ).thenAnswer((_) async => [createTestTask(projectId: 1)]);
    // Los anteproyectos ya no tienen tareas - solo proyectos
  }

  /// Esperar a que se complete la animación
  static Future<void> waitForAnimation(WidgetTester tester) async {
    // Usar pump() múltiples veces en lugar de pumpAndSettle() para evitar problemas de renderizado
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 100));
    await tester.pump(const Duration(milliseconds: 100));
  }

  /// Simular tap en un widget
  static Future<void> tapWidget(WidgetTester tester, Finder finder) async {
    await tester.tap(finder);
    await tester
        .pump(); // Usar pump() en lugar de pumpAndSettle() para evitar problemas de renderizado
  }

  /// Simular entrada de texto
  static Future<void> enterText(
    WidgetTester tester,
    Finder finder,
    String text,
  ) async {
    await tester.enterText(finder, text);
    await tester
        .pump(); // Usar pump() en lugar de pumpAndSettle() para evitar problemas de renderizado
  }

  /// Verificar que un widget está presente
  static void expectWidgetPresent(Finder finder) {
    expect(finder, findsOneWidget);
  }

  /// Verificar que un widget no está presente
  static void expectWidgetNotPresent(Finder finder) {
    expect(finder, findsNothing);
  }

  /// Verificar que un texto está presente
  static void expectTextPresent(String text) {
    expect(find.text(text), findsOneWidget);
  }

  /// Verificar que un texto no está presente
  static void expectTextNotPresent(String text) {
    expect(find.text(text), findsNothing);
  }
}
