// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/widget/widget_test_utils.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:frontend/models/models.dart' as _i3;
import 'package:frontend/services/anteprojects_service.dart' as _i6;
import 'package:frontend/services/auth_service.dart' as _i4;
import 'package:frontend/services/tasks_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnteproject_1 extends _i1.SmartFake implements _i3.Anteproject {
  _FakeAnteproject_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTask_2 extends _i1.SmartFake implements _i3.Task {
  _FakeTask_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComment_3 extends _i1.SmartFake implements _i3.Comment {
  _FakeComment_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i5.Stream<_i2.AuthState>.empty(),
          )
          as _i5.Stream<_i2.AuthState>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<bool> get isAdmin =>
      (super.noSuchMethod(
            Invocation.getter(#isAdmin),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> get isTutor =>
      (super.noSuchMethod(
            Invocation.getter(#isTutor),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> get isStudent =>
      (super.noSuchMethod(
            Invocation.getter(#isStudent),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.AuthResponse> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.User?> getCurrentUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserProfile, []),
            returnValue: _i5.Future<_i3.User?>.value(),
          )
          as _i5.Future<_i3.User?>);

  @override
  _i5.Future<void> updateProfile({
    required String? fullName,
    String? phone,
    String? biography,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #fullName: fullName,
              #phone: phone,
              #biography: biography,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> hasRole(_i3.UserRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#hasRole, [role]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [AnteprojectsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnteprojectsService extends _i1.Mock
    implements _i6.AnteprojectsService {
  MockAnteprojectsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Anteproject>> getAnteprojects() =>
      (super.noSuchMethod(
            Invocation.method(#getAnteprojects, []),
            returnValue: _i5.Future<List<_i3.Anteproject>>.value(
              <_i3.Anteproject>[],
            ),
          )
          as _i5.Future<List<_i3.Anteproject>>);

  @override
  _i5.Future<_i3.Anteproject?> getAnteproject(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAnteproject, [id]),
            returnValue: _i5.Future<_i3.Anteproject?>.value(),
          )
          as _i5.Future<_i3.Anteproject?>);

  @override
  _i5.Future<_i3.Anteproject> createAnteproject(_i3.Anteproject? anteproject) =>
      (super.noSuchMethod(
            Invocation.method(#createAnteproject, [anteproject]),
            returnValue: _i5.Future<_i3.Anteproject>.value(
              _FakeAnteproject_1(
                this,
                Invocation.method(#createAnteproject, [anteproject]),
              ),
            ),
          )
          as _i5.Future<_i3.Anteproject>);

  @override
  _i5.Future<_i3.Anteproject> updateAnteproject(
    int? id,
    _i3.Anteproject? anteproject,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAnteproject, [id, anteproject]),
            returnValue: _i5.Future<_i3.Anteproject>.value(
              _FakeAnteproject_1(
                this,
                Invocation.method(#updateAnteproject, [id, anteproject]),
              ),
            ),
          )
          as _i5.Future<_i3.Anteproject>);

  @override
  _i5.Future<void> submitAnteproject(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#submitAnteproject, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> approveAnteproject(int? id, String? comments) =>
      (super.noSuchMethod(
            Invocation.method(#approveAnteproject, [id, comments]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> rejectAnteproject(int? id, String? comments) =>
      (super.noSuchMethod(
            Invocation.method(#rejectAnteproject, [id, comments]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Anteproject>> getAnteprojectsByStatus(
    _i3.AnteprojectStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAnteprojectsByStatus, [status]),
            returnValue: _i5.Future<List<_i3.Anteproject>>.value(
              <_i3.Anteproject>[],
            ),
          )
          as _i5.Future<List<_i3.Anteproject>>);

  @override
  _i5.Future<List<_i3.Anteproject>> getTutorAnteprojects() =>
      (super.noSuchMethod(
            Invocation.method(#getTutorAnteprojects, []),
            returnValue: _i5.Future<List<_i3.Anteproject>>.value(
              <_i3.Anteproject>[],
            ),
          )
          as _i5.Future<List<_i3.Anteproject>>);
}

/// A class which mocks [TasksService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasksService extends _i1.Mock implements _i7.TasksService {
  MockTasksService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Task>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i5.Future<List<_i3.Task>>.value(<_i3.Task>[]),
          )
          as _i5.Future<List<_i3.Task>>);

  @override
  _i5.Future<List<_i3.Task>> getTasksByProject(int? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByProject, [projectId]),
            returnValue: _i5.Future<List<_i3.Task>>.value(<_i3.Task>[]),
          )
          as _i5.Future<List<_i3.Task>>);

  @override
  _i5.Future<_i3.Task?> getTask(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTask, [id]),
            returnValue: _i5.Future<_i3.Task?>.value(),
          )
          as _i5.Future<_i3.Task?>);

  @override
  _i5.Future<_i3.Task> createTask(_i3.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i5.Future<_i3.Task>.value(
              _FakeTask_2(this, Invocation.method(#createTask, [task])),
            ),
          )
          as _i5.Future<_i3.Task>);

  @override
  _i5.Future<_i3.Task> updateTask(int? id, _i3.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [id, task]),
            returnValue: _i5.Future<_i3.Task>.value(
              _FakeTask_2(this, Invocation.method(#updateTask, [id, task])),
            ),
          )
          as _i5.Future<_i3.Task>);

  @override
  _i5.Future<void> updateTaskStatus(int? id, _i3.TaskStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [id, status]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> assignUserToTask(int? taskId, int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#assignUserToTask, [taskId, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unassignUserFromTask(int? taskId, int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#unassignUserFromTask, [taskId, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Comment> addComment(
    int? taskId,
    String? content, {
    bool? isInternal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addComment,
              [taskId, content],
              {#isInternal: isInternal},
            ),
            returnValue: _i5.Future<_i3.Comment>.value(
              _FakeComment_3(
                this,
                Invocation.method(
                  #addComment,
                  [taskId, content],
                  {#isInternal: isInternal},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.Comment>);

  @override
  _i5.Future<List<_i3.Comment>> getTaskComments(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskComments, [taskId]),
            returnValue: _i5.Future<List<_i3.Comment>>.value(<_i3.Comment>[]),
          )
          as _i5.Future<List<_i3.Comment>>);

  @override
  _i5.Future<void> updateKanbanPosition(int? taskId, int? newPosition) =>
      (super.noSuchMethod(
            Invocation.method(#updateKanbanPosition, [taskId, newPosition]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Task>> getTasksByStatus(_i3.TaskStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByStatus, [status]),
            returnValue: _i5.Future<List<_i3.Task>>.value(<_i3.Task>[]),
          )
          as _i5.Future<List<_i3.Task>>);

  @override
  _i5.Future<List<_i3.Task>> getTasksByComplexity(
    _i3.TaskComplexity? complexity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByComplexity, [complexity]),
            returnValue: _i5.Future<List<_i3.Task>>.value(<_i3.Task>[]),
          )
          as _i5.Future<List<_i3.Task>>);

  @override
  _i5.Future<List<_i3.Task>> getTasksWithUpcomingDeadline({
    int? daysAhead = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksWithUpcomingDeadline, [], {
              #daysAhead: daysAhead,
            }),
            returnValue: _i5.Future<List<_i3.Task>>.value(<_i3.Task>[]),
          )
          as _i5.Future<List<_i3.Task>>);

  @override
  _i5.Future<void> deleteTask(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
