import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:mockito/mockito.dart';
import 'package:mockito/annotations.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'package:frontend/services/auth_service.dart';
import 'package:frontend/services/anteprojects_service.dart';
import 'package:frontend/services/tasks_service.dart';
import 'package:frontend/blocs/auth_bloc.dart';
import 'package:frontend/blocs/anteprojects_bloc.dart';
import 'package:frontend/blocs/tasks_bloc.dart';
import 'package:frontend/models/user.dart';
import 'package:frontend/models/anteproject.dart';
import 'package:frontend/models/task.dart';
import 'package:frontend/l10n/app_localizations.dart';
import 'package:supabase_flutter/supabase_flutter.dart' as supabase; // Import Supabase AuthState
import 'widget_test_utils.mocks.dart';

// Generar mocks
@GenerateMocks([AuthService, AnteprojectsService, TasksService])
import 'widget_test_utils.mocks.dart';

/// Utilidades comunes para tests de widgets
class WidgetTestUtils {
  /// Crear MaterialApp con BlocProvider para testing
  static Widget createTestApp({
    required Widget child,
    List<BlocProvider> blocProviders = const [],
  }) {
    return MaterialApp(
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      locale: const Locale('es', 'ES'),
      home: MultiBlocProvider(
        providers: blocProviders,
        child: child,
      ),
    );
  }

  /// Crear MaterialApp con navegación para testing
  static Widget createTestAppWithNavigation({
    required Widget child,
    List<BlocProvider> blocProviders = const [],
  }) {
    return MaterialApp(
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      locale: const Locale('es', 'ES'),
      routes: {
        '/': (context) => child,
        '/login': (context) => const Scaffold(body: Text('Login')),
        '/dashboard': (context) => const Scaffold(body: Text('Dashboard')),
      },
      home: MultiBlocProvider(
        providers: blocProviders,
        child: child,
      ),
    );
  }

  /// Crear usuario de prueba
  static User createTestUser({
    int id = 1,
    String email = 'test@example.com',
    String fullName = 'Test User',
    UserRole role = UserRole.student,
    UserStatus status = UserStatus.active,
  }) {
    final now = DateTime.now();
    return User(
      id: id,
      email: email,
      fullName: fullName,
      role: role,
      status: status,
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Crear anteproyecto de prueba
  static Anteproject createTestAnteproject({
    int id = 1,
    String title = 'Test Anteproject',
    String description = 'Test Description',
    ProjectType projectType = ProjectType.execution,
    String academicYear = '2024-2025',
    AnteprojectStatus status = AnteprojectStatus.draft,
    int tutorId = 1,
  }) {
    final now = DateTime.now();
    return Anteproject(
      id: id,
      title: title,
      projectType: projectType,
      description: description,
      academicYear: academicYear,
      expectedResults: {'result1': 'Expected result 1'},
      timeline: {'phase1': 'Phase 1 description'},
      status: status,
      tutorId: tutorId,
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Crear tarea de prueba
  static Task createTestTask({
    int id = 1,
    String title = 'Test Task',
    String description = 'Test Description',
    int projectId = 1,
    TaskStatus status = TaskStatus.pending,
    TaskComplexity complexity = TaskComplexity.medium,
  }) {
    final now = DateTime.now();
    return Task(
      id: id,
      projectId: projectId,
      title: title,
      description: description,
      status: status,
      complexity: complexity,
      kanbanPosition: 0,
      isAutoGenerated: false,
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Configurar mocks básicos
  static void setupBasicMocks({
    required MockAuthService mockAuthService,
    required MockAnteprojectsService mockAnteprojectsService,
    required MockTasksService mockTasksService,
  }) {
    // Mock AuthService
    when(mockAuthService.isAuthenticated).thenReturn(true);
    when(mockAuthService.authStateChanges).thenAnswer(
      (_) => const Stream.empty(),
    );

    // Mock AnteprojectsService
    when(mockAnteprojectsService.getAnteprojects()).thenAnswer(
      (_) async => [createTestAnteproject()],
    );

    // Mock TasksService
    when(mockTasksService.getTasks()).thenAnswer(
      (_) async => [createTestTask()],
    );
  }

  /// Esperar a que se complete la animación
  static Future<void> waitForAnimation(WidgetTester tester) async {
    await tester.pumpAndSettle();
  }

  /// Simular tap en un widget
  static Future<void> tapWidget(WidgetTester tester, Finder finder) async {
    await tester.tap(finder);
    await tester.pumpAndSettle();
  }

  /// Simular entrada de texto
  static Future<void> enterText(WidgetTester tester, Finder finder, String text) async {
    await tester.enterText(finder, text);
    await tester.pumpAndSettle();
  }

  /// Verificar que un widget está presente
  static void expectWidgetPresent(Finder finder) {
    expect(finder, findsOneWidget);
  }

  /// Verificar que un widget no está presente
  static void expectWidgetNotPresent(Finder finder) {
    expect(finder, findsNothing);
  }

  /// Verificar que un texto está presente
  static void expectTextPresent(String text) {
    expect(find.text(text), findsOneWidget);
  }

  /// Verificar que un texto no está presente
  static void expectTextNotPresent(String text) {
    expect(find.text(text), findsNothing);
  }
}
