// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/mocks/auth_service_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/models/models.dart' as _i5;
import 'package:frontend/services/auth_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i2.AuthState>.empty(),
          )
          as _i4.Stream<_i2.AuthState>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<bool> get isAdmin =>
      (super.noSuchMethod(
            Invocation.getter(#isAdmin),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> get isTutor =>
      (super.noSuchMethod(
            Invocation.getter(#isTutor),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> get isStudent =>
      (super.noSuchMethod(
            Invocation.getter(#isStudent),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.AuthResponse> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResponse>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.User?> getCurrentUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserProfile, []),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<void> updateProfile({
    required String? fullName,
    String? phone,
    String? biography,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #fullName: fullName,
              #phone: phone,
              #biography: biography,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasRole(_i5.UserRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#hasRole, [role]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthServiceForTests extends _i1.Mock implements _i3.AuthService {
  MockAuthServiceForTests() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i2.AuthState>.empty(),
          )
          as _i4.Stream<_i2.AuthState>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<bool> get isAdmin =>
      (super.noSuchMethod(
            Invocation.getter(#isAdmin),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> get isTutor =>
      (super.noSuchMethod(
            Invocation.getter(#isTutor),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> get isStudent =>
      (super.noSuchMethod(
            Invocation.getter(#isStudent),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.AuthResponse> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResponse>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.User?> getCurrentUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserProfile, []),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<void> updateProfile({
    required String? fullName,
    String? phone,
    String? biography,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #fullName: fullName,
              #phone: phone,
              #biography: biography,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasRole(_i5.UserRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#hasRole, [role]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
